set_property SRC_FILE_INFO {cfile:C:/Users/rafcal0v/riscv-steel-tests/hello-world/cmod-a7/cmod-a7.srcs/constrs_1/new/hello-world-cmod-a7-constraints.xdc rfile:../../../cmod-a7.srcs/constrs_1/new/hello-world-cmod-a7-constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports clock]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports reset]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports uart_rx]
